# Official Loki Helm chart configuration for local development
loki:
  # Use SimpleScalable mode for local/dev environments
  deploymentMode: SimpleScalable

  # Enable MinIO for object storage (simple for local dev)
  minio:
    enabled: true
    replicas: 1
    persistence:
      size: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

  # Loki configuration
  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    storage:
      type: s3
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      s3:
        s3ForcePathStyle: true
        insecure: true

    schemaConfig:
      configs:
        - from: 2024-04-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    limits_config:
      retention_period: 168h  # 7 days
      max_query_lookback: 168h

    compactor:
      retention_enabled: true
      delete_request_store: s3

  # Backend (read component)
  backend:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Read component
  read:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Write component
  write:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Gateway
  gateway:
    enabled: true
    replicas: 1
    service:
      type: ClusterIP
      port: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

  # Monitoring disabled for simplicity
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false

  # Test disabled
  test:
    enabled: false

  # Disable memcached caches for local dev (they require too much memory)
  chunksCache:
    enabled: false

  resultsCache:
    enabled: false
