replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.4.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

admin:
  username: user
  password: password

# Keycloak command arguments
# Use "start-dev" for development mode
command: "start-dev"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
