# Official Tempo Helm chart configuration for local development
tempo:
  # Use single binary for simplicity in local dev
  tempo:
    repository: grafana/tempo
    tag: 2.6.1
    pullPolicy: IfNotPresent

    # Tempo configuration
    structuredConfig:
      auth_enabled: false

      server:
        http_listen_port: 3100
        grpc_listen_port: 9095

      distributor:
        receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
              http:
                endpoint: 0.0.0.0:4318
          jaeger:
            protocols:
              grpc:
                endpoint: 0.0.0.0:14250
              thrift_http:
                endpoint: 0.0.0.0:14268
              thrift_compact:
                endpoint: 0.0.0.0:6831
              thrift_binary:
                endpoint: 0.0.0.0:6832
          zipkin:
            endpoint: 0.0.0.0:9411

      ingester:
        max_block_duration: 5m

      compactor:
        compaction:
          block_retention: 168h  # 7 days

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          pool:
            max_workers: 100
            queue_depth: 10000

      querier:
        frontend_worker:
          frontend_address: tempo-query-frontend:9095

      query_frontend:
        search:
          duration_slo: 5s
          throughput_bytes_slo: 1.073741824e+09
        trace_by_id:
          duration_slo: 5s

      metrics_generator:
        registry:
          external_labels:
            source: tempo
            cluster: local
        storage:
          path: /var/tempo/wal
          remote_write:
            - url: http://prometheus-kube-prometheus.default.svc.cluster.local:9090/api/v1/write
              send_exemplars: true

      overrides:
        defaults:
          metrics_generator:
            processors: [service-graphs, span-metrics]

  # Use single binary deployment for simplicity
  singleBinary:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      size: 10Gi

  # Service configuration
  service:
    type: ClusterIP

  # ServiceMonitor disabled for simplicity
  serviceMonitor:
    enabled: false

  # Disable distributed mode components
  distributor:
    enabled: false
  ingester:
    enabled: false
  compactor:
    enabled: false
  querier:
    enabled: false
  queryFrontend:
    enabled: false
  metricsGenerator:
    enabled: false

  # Simple persistence for local dev
  persistence:
    enabled: true
    size: 10Gi
