apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-prometheus.fullname" . }}
  labels:
    {{ include "kube-prometheus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "kube-prometheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "kube-prometheus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: storage
          mountPath: /prometheus
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "kube-prometheus.fullname" . }}
      - name: storage
        emptyDir: {}
