apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{ include "grafana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: grafana
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: GF_PATHS_PROVISIONING
          value: /etc/grafana/provisioning
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "{{ .Values.grafana.anonymousEnabled }}"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "{{ .Values.grafana.anonymousOrgRole }}"
        - name: GF_SECURITY_ADMIN_USER
          value: "{{ .Values.grafana.adminUser }}"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "{{ .Values.grafana.adminPassword }}"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: datasources
        configMap:
          name: {{ include "grafana.fullname" . }}-datasources
