replicaCount: 1

image:
  repository: grafana/grafana
  tag: "11.4.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

grafana:
  adminUser: admin
  adminPassword: admin
  anonymousEnabled: true
  anonymousOrgRole: Admin

datasources:
  prometheus:
    url: http://prometheus-kube-prometheus.default.svc.cluster.local:9090
  tempo:
    url: http://tempo.default.svc.cluster.local:3100
  loki:
    url: http://loki-gateway.default.svc.cluster.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
