apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - {{ .Values.command }}
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: {{ .Values.admin.username | quote }}
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: {{ .Values.admin.password | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
