apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: kafka
    port: {{ .Values.service.port }}
    targetPort: kafka
    protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
