apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-controller-headless
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: kafka
    port: {{ .Values.service.port }}
    targetPort: kafka
    protocol: TCP
  - name: controller
    port: 29093
    targetPort: controller
    protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
